repos:
  - repo: local
    hooks:
    -   id: pytest
        name: pytest
        language: system
        entry: venv/bin/pytest -v 
        atways_run: true
        pass_filenames: false
        stages: [pre-commit]

  - repo: local
    hooks:
      - id: requirements
        name: requirements
        entry: bash -c 'venv/bin/pip3 freeze > requirements.txt && git add requirements.txt'
        language: system
        pass_filenames: false
        stages: [pre-commit]